[build]
builder = "dockerfile"
dockerfilePath = "./Dockerfile"

[deploy]
restartPolicyType = "on-failure"
healthcheckPath = "/health"
healthcheckTimeout = 30

[env]
NODE_ENV = "production"
SERVICE_TYPE = "mcp-server"